import { defineWompo } from 'wompo';
import getPageLayout, { Contents } from '../../utils/getPageLayout.js';
import Code from '../../components/Code.js';
import { Link } from 'wompo-router';

const content: Contents = {
	title: 'Using Typescript with Wompo',
	description: 'How to use Typescript with Wompo to improve your code and make it bug-proof.',
	sections: [
		{
			title: 'Usage',
			id: 'usage',
			content: (
				<>
					<p>
						Wompo is built completely with Typescript, so type checking is enabled by default when
						using Wompo.
						<br />
						If you are a Typescript user, you probably want to add types to your component's props,
						or export the interface of the Component's instance types (usually when you use the{' '}
						<Link to='/docs/hooks/useExposed'>useExposed</Link> hook). This is very common and can
						benefit a lot when used in combination with JSX. If you use typescript, you can enable
						JSX by writing the following options in your <b>tsconfig.json</b> file:
					</p>
					<Code
						code={`
              { 
                "compilerOptions": {
                  // ...
                  "jsx": "react-jsx",
                  "jsxImportSource": "wompo",
                  // ...
                } 
              }
            `}
						language='js'
					/>
					<p>
						You can see all the types that Wompo exposes on the{' '}
						<Link to='/docs/apis#types'>APIs</Link> page. Here we are going to mainly analyze the{' '}
						<b>WompoProps</b> and <b>WompoElement</b> interfaces.
					</p>
				</>
			),
		},
		{
			title: 'Example: user card',
			id: 'user-card-example',
			content: (
				<>
					<p>
						The majority of your components will probably accept some props. By default, every
						component has the following props:
						<ul>
							<li>
								<b>children</b> - the children of your component
							</li>
							<li>
								<b>styles</b> - the class names generated by the <code>cssModule</code> option
							</li>
						</ul>
						These are defined by the <b>WompoProps</b> interface. If you want your component to
						accept more props, you can define your own interface by extending <b>WompoProps</b>.
						<br />
						Let's create a <code>UserCard</code> component, using also JSX.
					</p>
					<Code
						code={`
              interface UserCardProps extends WompoProps {
                name: string;
                lastName: string;
                age: number;
                additionalInfo?: {
                  hairColor: string;
                  height: number;
                }
              }

              export default function UserCard({ name, lastName, age, additionalInfo, styles: s }: UserCardProps) {
                return (
                  <div class={s.card}>
                    <h3>{name} {lastName}, {age}yo</h3>
                    {additionalInfo && <p>
                      Hair color: {additionalInfo.hairColor}<br/>
                      Height: {additionalInfo.height}
                    </p>}
                  </div>
                )
              }
            `}
						language='ts'
					/>
					<p>
						If then you want to use the <code>UserCard</code> component inside another Component,
						typescript will warn you saying that the <i>name, lastname, and age</i> props are
						mandatory. The <i>additionalInfo</i> prop is optional.
					</p>
				</>
			),
		},
		{
			title: 'Example: modal',
			id: 'modal-example',
			content: (
				<>
					<p>
						What if you wanto to expose some methods and then call them on another component? That's
						the perfect example for a Modal. Let's see how you can do it with Typescript.
					</p>
					<Code
						code={`
              export interface ModalElement extends WompoElement {
                open: () => void;
                close: () => void;
              }

              export default function Modal() {
                const [open, setOpen] = useState(false);
                useExposed({
                  open: () => setOpen(true),
                  close: () => setOpen(false)
                })
                return ( 
                  <div>...</div>
                );
              }
            `}
						language='ts'
					/>
					<p>Then, inside your app:</p>
					<Code
						code={`
              import Modal, { type ModalElement } from './Modal';

              export default function App() {
                const modalRef = useRef<ModalElement>(null);
                const openModal = () => {
                  modalRef.current.open();
                }
                return ( 
                  <div>
                    <button onClick={openModal}>Open modal</button>
                    <Modal ref={modalRef} />
                  </div>
                );
              }
            `}
						language='ts'
					/>
					<p>
						The <Link to='/docs/hooks/useRef'>useRef</Link> hook is Generic. By using the{' '}
						<b>ModalElement</b> interface as a type for the hook, Wompo will know that the{' '}
						<code>modalRef</code> variable will contain an instance of the <code>Modal</code>{' '}
						element.
					</p>
				</>
			),
		},
	],
};

export default function TypescriptPage() {
	return getPageLayout(content);
}

defineWompo(TypescriptPage, {
	name: 'typescript-page',
});
